name: Build and Publish

on:
  push:
    branches: ['*']
  pull_request:
    branches: [main]

permissions:
  contents: write 
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Leer mod_version desde gradle.properties
        id: version
        uses: BrycensRanch/read-properties-action@v1
        with:
          file: gradle.properties
          property: mod_version
          default: 0.0.1

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.mod_version }}
          name: Release ${{ steps.version.outputs.mod_version }}
          body: Automatic release from commit ${{ github.sha }}.
          draft: false
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}